### ISSUE TITLE
Upload the files on SFTP to other server

### ISSUE THREAD

**Issue by biulas** [wlabarron/submit-show#107]
Hello Barron,

Is there anyway easy that remote server upload of files can be implemented, in stead of local storage or S3?

**Comment by wlabarron** [comment]
Hello, I recommend using [`rclone mount`](https://rclone.org/commands/rclone_mount/) to mount the remote storage location to your server as a network drive, then point the Submit Show tool to that network drive as local storage.

**Comment by biulas** [comment]
Thanks Barron for the reply. I've managed to use that tool to mount an external volume,
