### ISSUE TITLE
Scroll down to DIV upon pressing first button

### ISSUE THREAD

**Issue by biulas** [wlabarron/submit-show#128]
Hello Barron!

I've been struggling to code in a "scroll down to view" when the users press the first upload button. The idea would be to scroll down automatically to a speficic DIV (like the image mixcloud DIV). When we press the first button, user has to scroll down to check the remaining form fields.

Im not very code savy but I already tried some solutions online and dont work. I've 

Can you help?

Many thanks for your help.

**Comment by wlabarron** [comment]
Are you seeing users struggle with this? I'm not a huge fan of taking over control of scrolling when we don't need to, and I think the form fields right next to the button should be clear enough.

**Comment by biulas** [comment]
Some users do. But is more because if hidden some fields, so nothing do to with your code. I was trying to get some help in achiving this, but i guess its custom coding. :)
