### ISSUE TITLE
`,` missing after `smtpRecipient` config value

### ISSUE THREAD

**Issue by biulas** [wlabarron/submit-show#14]
Hey, congrats for the great script! I've configured database with default table and fields, created config.php but still I can't seem to run it.  

When I visit the page, I get error 500. 

It has to be something related to config im sure, cause commented out the first PHP lines on index.php where you call some data and the simple HTML version runs.

**Comment by wlabarron** [comment]
Hi @biulas, thank you! Can you check your PHP error log? There should be an entry with a line number or similar which will help me find the problem.

**Comment by biulas** [comment]
Hey thanks for quick answer, below the log:

2021-05-05 08:38:46.337623 [NOTICE] [3855720] [172.68.242.201:34330#APVH_www.umt.radio:443] [STDERR] PHP Parse error:  syntax error, unexpected ''loggingLevel'' (T_CONSTANT_ENCAPSED_STRING), expecting ')' in /home/neuzaclo/domains/umt.radio/public_html/mix/processing/config.php on line 82

**Comment by wlabarron** [comment]
In `config.php`, add a `,` after `'smtpRecipient' => ''`, so the whole line is `'smtpRecipient' => '',` (or with an email address between the quotes). That should get you running.

The comma is missing in the template. I'll leave this issue open til I update the file. Thank you for reporting!
