### ISSUE TITLE
Missing Composer vendor/dependencies 

### ISSUE THREAD

**Issue by biulas** [wlabarron/submit-show#15]
Hello again,

Have different error know, it seems project misses vendor files.

Has i understand they are specific to the project.

021-05-05 09:26:20.631940 [NOTICE] [4103901] [172.68.242.175:61322#APVH_www.umt.radio:443] [STDERR] PHP Warning:  require_once(/home/neuzaclo/domains/umt.radio/public_html/mix/processing/vendor/autoload.php): failed to open stream: No such file or directory in /home/neuzaclo/domains/umt.radio/public_html/mix/processing/databaseConnections.php on line 6

Thanks for the support!!

**Comment by wlabarron** [comment]
Hello! Run the command `composer install` in the `/home/neuzaclo/domains/umt.radio/public_html/mix/` directory.
