### ISSUE TITLE
Error parsing the database info

### ISSUE THREAD

**Issue by biulas** [wlabarron/submit-show#16]
Any chance you could share the database structure example or even SQL file has example? 

Having a hard time getting this right.

PHP error log:

[09-May-2021 05:57:28 UTC] PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on bool in /var/www/html/mix/index.php:115
Stack trace:
#0 {main}
  thrown in /var/www/html/mix/index.php on line 115

So im guessing my tables are not well configured.

Thanks for the help

**Comment by wlabarron** [comment]
Hi @biulas -- thanks for opening this. I'll provide proper installation instructions which cover this as part of the [v1 release](https://github.com/wlabarron/submit-show/projects/1). I'm going to close this issue now as it's been superseded by #28.

**Comment by wlabarron** [comment]
Hi @biulas, take a look here: https://github.com/wlabarron/submit-show/releases/tag/v1. It's probably easiest to delete the folder you're currently working in and start again with the new installation instructions.
