### ISSUE TITLE
Absolute instead of relative paths used in `script.js` for retrieving saved show information

### ISSUE THREAD

**Issue by biulas** [wlabarron/submit-show#40]
Hey Barron,

Wonderful updates, I've successfully implemented the script with SAML using WordPress has IDP and its working beautifully!

Sole issue - it seems that upon choosing the show, even if previously ticked regarding saved information, when selecting that same show, the information saved regarding that show does not populate the fields. I got no logs oh PHP-FM. 

I can provide full access to server if you believe it would be more easier to help.

Many thanks, I would gladly buy this software, its exactly what I needed!

**Comment by wlabarron** [comment]
Glad it's working for you! In the first instance, can you take a look in the database table `saved_info` and check it's populated with the information you expect? You should see your show's ID (matching the one from your JSON file of shows) along with the description you saved, and some reference of an image if applicable. There should also be some tags in the `saved_tags` table. Is there anything there?

**Comment by biulas** [comment]
![2021-05-22 18_46_23-149 28 150 42 _ localhost _ shows _ saved_info _ phpMyAdmin 5 0 4deb2~bpo10+1+bi](https://user-images.githubusercontent.com/37944005/119225461-16c79380-bb2e-11eb-8a59-5c719d1d08ee.png)

Yes the information is well recorded on database as you can see attached. Im still using your JSON with show ID 1 and 2 to test. When I upload a file, select show 2 and continue, it does not load the data on the database, even thought its there with correct ID. 

The save_tags also have recorded information on database with correct show ids.

![2021-05-22 18_49_40-149 28 150 42 _ localhost _ shows _ saved_tags _ phpMyAdmin 5 0 4deb2~bpo10+1+bi](https://user-images.githubusercontent.com/37944005/119225528-7de54800-bb2e-11eb-93f5-c229fad52a5b.png)

**Comment by wlabarron** [comment]
Hm, okay. When you press "Upload and Continue" on the form after choosing one of the shows, can you see if any errors appear in your browser console? In the Network tab of the browser developer tools, there should be two XHR/fetch requests, one for `data.php` and one for `image.php`. For show ID 2, where there's an image and data, both of those requests should be status 200 OK.

Which browser and version are you using?

**Comment by biulas** [comment]
Fixed the path on JS file, both PHP where 404! Thanks, all working! I installed this script on a domain folder, not root, so I had to had the folder name to /resources/default/ call on JS.

**Comment by wlabarron** [comment]
Ah! Okay, I'll fix that in the next release. When it's out and you want to upgrade, you'll probably need to revert your own change as git will refuse to pull if you've uncommitted local changes (something like `git reset --hard HEAD` before following the upgrade instructions should do the job).
