### ISSUE TITLE
Send link for file on admin notification 

### ISSUE THREAD

**Issue by biulas** [wlabarron/submit-show#48]
Possible to send a link on body of the emial admin notification on show submission? 

Same way has when Mixcloud published notification? 

The link is to allow admin to upload or download the file directly to transit for radio platform.

**Comment by biulas** [comment]
Ah ok. Thing is we use a cloud solution for the radio feed and it only allows its own website upload or via URL.  No API no FTP.

 

Thanks!

**Comment by wlabarron** [comment]
I'd probably suggest looking into a separate tool to get the link you need. The nginx or Apache directory listing function might be ideal for this, and there are various options for S3.

I feel a system to manage and create download links for files is out of scope for now (or at least the things I have time to work on). S3 in particular would need some way to create authenticated links to support private buckets, which moves us towards a submission management and admin frontend which doesn't exist at the moment.

**Comment by wlabarron** [comment]
(making notes to myself here)
Another thing to think about with this is the fact that notification emails are sent before files are actually put into their final storage location, so that would also need rearranged.
